ui/Models/Customer.cs
using System;

namespace ui.Models
{

    //Customer model to map list of customers fetched from API
    public class Customer
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
    }
}

ui/Models/ErrorViewModel.cs
using System;

namespace ui.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ui/Controllers/CustomersController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ui.Models;
using RestSharp;
using Newtonsoft.Json;

//Controller to display list of customers with status Hot
namespace ui.Controllers
{
    public class CustomersController : Controller
    {
        private IEnumerable<Customer> customers;
        private APIClient client;
        private RestResponse response;
        
        //User must be authorized through Auth0 to access this route
        [Authorize]
        public async Task<IActionResult> Index()
        {
            //If user authenticated
            if (User.Identity.IsAuthenticated)
            {
                //Getting access token to provide in request header while calling backend API
                string accessToken = await HttpContext.GetTokenAsync("access_token");
                client = new APIClient();
                //Sneding GET request to backend API to fetch list of customers with status Hot
                response = client.GetRequest("/customers", accessToken);
            }
            if(response.Content != null) {
                //Mapping data to Customer Model
                customers = JsonConvert.DeserializeObject<List<Customer>>(response.Content);
                
                //Passing list of customers to UI
                return View(customers);
            }
            ViewData["Error"] = "No customer data found or Customer API is not running at the backend";
            //No data available or API is down
            return View();
        }
    }
}

ui/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using ui.Models;

namespace ui.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ui/Controllers/UserAccountsController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ui.Models;

namespace ui.Controllers
{
    public class UserAccountsController : Controller
    {
        //Auth0 login route
        public async Task Login(string returnUrl = "/Customers/Index")
        {
            //Redirecting user to "Customer/Index" directly after login
            await HttpContext.ChallengeAsync("Auth0", new AuthenticationProperties() { RedirectUri = returnUrl });
        }

        //Auth0 logout route
        [Authorize]
        public async Task Logout()
        {
            await HttpContext.SignOutAsync("Auth0", new AuthenticationProperties
            {
                // Where Auth0 should redirect the user after a logout.
                RedirectUri = Url.Action("Index", "Home")
            });
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }
    }
}

ui/Views/Customers/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model IEnumerable<ui.Models.Customer>

@if(Model != null) {
    <div class="customers">
        <h1>Customers List</h1>
        <ul id="customers-list">
            @foreach(var customer in Model) {
                <li>
                    <span class="customer-name">@customer.Name</span>
                    <span class="customer-detail">Email: @customer.Email</span>
                    <span class="customer-detail">Mobile: @customer.Mobile</span>
                    <span class="customer-detail">Address: @customer.Address</span>
                    <span class="customer-detail customer-status">Status: @customer.Status</span>
                </li>
            }
        </ul>
    </div>
}

ui/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

        <div class="customers" style="text-align: center">
            <img src="~/images/logo.png" style="width: 200px; height:auto" >
            <h1>Welcome To Customers Viewer</h1>
            <p style="text-align:center">Please login to see the list of the customers with status Hot</p>
        </div>

ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Customers</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/customers.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img src="~/images/logo.png" style="width:40px; height: auto;margin-top:-10px;" >
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Customers" asp-action="Index">View Customers</a></li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                @if (User.Identity.IsAuthenticated)
                {
                    <li>Hello @User.Identity.Name!</li>
                    <li><a  asp-controller="UserAccounts" asp-action="Logout">Logout</a></li>
                }
                else
                {
                    <li><a asp-controller="UserAccounts" asp-action="Login">Login</a></li>
                }
            </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Customers</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>